version: 2.1

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-2004:202201-02

jobs:
  run_starlark:
    executor: ubuntu_vm
    resource_class: xlarge
    steps:

      # Set up Kurtosis
      - run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
      - checkout

      # We don't send metrics to avoid polluting our logs
      - run: kurtosis config init dont-send-metrics

      - run: kurtosis engine restart

      - run: |
          kurtosis run ${PWD} '{"num_nodes": 3, "monitoring_enabled": true}'
  
workflows:
  build:
    jobs:
      # -- PR check jobs ------------------------------------------
      - run_starlark:
          filters:
            branches:
              ignore:
                - main
